Fingertip testing
t184256/fingertip pull request #29
Opened 2021-04-01 13:46 UTC by shigaraki0

@t184256

2021-04-01 22:59 UTC, t184256 requested changes
+ rebase on top of current master

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.ks
> +%packages --timeout 900
please try adding `--excludeWeakdeps` for even less packages

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.ks
> +
empty line at the end of the file

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +#http://ftp.fi.muni.cz/pub/linux/centos/8-stream/
this isn't used here

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +                    fips=False):
Please remove the `fips` parameter, I don't see anyone using it in the close future.
Or allow passing custom stuff to `-append` instead.

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +    URL = 'http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/'
Please move the constant to the top of the file outside of the functions (and maybe the comment will become unnecessary).

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +        append = ('ks=http://mock/ks console=ttyS0 ' + 'inst.text ' + 'inst.notmux ' + 'inst.cmdline ' +
1) keep lines shorter than 79 characters
2) why do that `'a ' + 'b ' + 'c '` when you can do `'a b c '`?

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +        m.log.info('Centos installation finished')
`CentOS`. Or, better, `CentOS Stream`.

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +        m.release = '8'
I don't think this is needed; IIUC, CentOS Stream doesn't have minor releases.

2021-04-01 22:59 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +
Empty line at the end of the file.

2021-04-07 10:49 UTC, t184256 requested changes
Seems to work OK. Please address two very minor things and add yourself to CONTRIBUTORS.

2021-04-07 10:49 UTC, t184256 commented on fingertip/plugins/os/centos-stream.py
> +            m.console.expect('Running post-installation scripts')
Better expect `Installation complete`.

2021-04-07 10:49 UTC, t184256 commented on fingertip/plugins/os/centos-stream.ks
> +
remove the empty line, please

2021-04-07 13:21 UTC, shigaraki0 commented
@t184256

2021-04-07 20:41 UTC, merged

2021-04-07 20:42 UTC, t184256 commented
LGTM!